

def title(): 
	print("  _____ _                 _  __              _ ")
	print(" / ____(_)          /\   | |/ _|            | |")
	print(" | (___ _ _ __     /  \  | | |_ _ __ ___  __| |")
	print(" \___ \| | '__|   / /\ \ | |  _| '__/ _ \/ _` |")
	print(" ____) | | |     / ____ \| | | | | |  __/ (_| |")
	print("|_____/|_|_|    /_/    \_\_|_| |_|  \___|\__,_|")
	print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
	print("				              |")       
	print("              ▄▄▄▄▄▄▄▄▄▄            	      |")
	print("             ▓        _ ▓  		      |")
	print("            ▓  |         ▓ 		      |")
	print("            ▓            ▓		      |")
	print("         ▓▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ ▓		      |")
	print("         ▀▀█▀▀▀▀▀▀▀▀▀▀▀▀▀█▀▀                  |")      
	print("           ▓  ▀█▀   ▄▀▀▄ ▓    ( How May I     |")     
	print("            ▓     | ▀▄▄▀ ▓             	      |")
	print("            ▓    ___  |  ▓   O   Serve?  )    |")   
	print("            ▓    ▀▀▀  |_ ▓ o                  |")
	print("             ▓    .     ▓                     |")
	print("              ▀▀▀▀▀▀▀▀▀▀                      |")
	print("                ▓▓▄▓▓                         |")
	print("                 ▀ ▀                          |")
	print("  Adb Shell Account Checker - v.1.3")
	print("  ----------------------------------\n")

def Checking():         
	print("  _____ _                 _  __              _ ")
	print(" / ____(_)          /\   | |/ _|            | |")
	print(" | (___ _ _ __     /  \  | | |_ _ __ ___  __| |")
	print(" \___ \| | '__|   / /\ \ | |  _| '__/ _ \/ _` |")
	print(" ____) | | |     / ____ \| | | | | |  __/ (_| |")
	print("|_____/|_|_|    /_/    \_\_|_| |_|  \___|\__,_|")
	print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
	print("				              |")       
	print("              ▄▄▄▄▄▄▄▄▄▄            	      |")
	print("             ▓        _ ▓  		      |")
	print("            ▓  |         ▓ 		      |")
	print("            ▓            ▓		      |")
	print("         ▓▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ ▓		      |")
	print("         ▀▀█▀▀▀▀▀▀▀▀▀▀▀▀▀█▀▀                  |")      
	print("           ▓  ▀█▀   ▄▀▀▄ ▓    ( Checking      |")     
	print("            ▓     | ▀▄▄▀ ▓       Accounts     |")
	print("            ▓    ___  |  ▓   O      m'lord  ) |")   
	print("            ▓    ▀▀▀  |_ ▓ o                  |")
	print("             ▓    .     ▓                     |")
	print("              ▀▀▀▀▀▀▀▀▀▀                      |")
	print("                ▓▓▄▓▓                         |")
	print("                 ▀ ▀                          |")
	print("  Adb Shell Account Checker - v.1.3")
	print("  ----------------------------------\n")

def Valid():         
	print("  _____ _                 _  __              _ ")
	print(" / ____(_)          /\   | |/ _|            | |")
	print(" | (___ _ _ __     /  \  | | |_ _ __ ___  __| |")
	print(" \___ \| | '__|   / /\ \ | |  _| '__/ _ \/ _` |")
	print(" ____) | | |     / ____ \| | | | | |  __/ (_| |")
	print("|_____/|_|_|    /_/    \_\_|_| |_|  \___|\__,_|")
	print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
	print("				              |")       
	print("              ▄▄▄▄▄▄▄▄▄▄            	      |")
	print("             ▓        _ ▓  		      |")
	print("            ▓  |         ▓ 		      |")
	print("            ▓            ▓		      |")
	print("         ▓▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ ▓		      |")
	print("         ▀▀█▀▀▀▀▀▀▀▀▀▀▀▀▀█▀▀                  |")      
	print("           ▓  ▀█▀   ▄▀▀▄ ▓    ( Account      |")     
	print("            ▓     | ▀▄▄▀ ▓       is Valid,    |")
	print("            ▓    ___  |  ▓   O   but might be |")   
	print("            ▓    ▀▀▀  |_ ▓ o     expired      |")
	print("             ▓    .     ▓        m'lord  )    |")
	print("              ▀▀▀▀▀▀▀▀▀▀                      |")
	print("                ▓▓▄▓▓                         |")
	print("                 ▀ ▀                          |")
	print("  Adb Shell Account Checker - v.1.3")
	print("  ----------------------------------\n")

def Invalid():         
	print("  _____ _                 _  __              _ ")
	print(" / ____(_)          /\   | |/ _|            | |")
	print(" | (___ _ _ __     /  \  | | |_ _ __ ___  __| |")
	print(" \___ \| | '__|   / /\ \ | |  _| '__/ _ \/ _` |")
	print(" ____) | | |     / ____ \| | | | | |  __/ (_| |")
	print("|_____/|_|_|    /_/    \_\_|_| |_|  \___|\__,_|")
	print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
	print("				              |")       
	print("              ▄▄▄▄▄▄▄▄▄▄            	      |")
	print("             ▓        _ ▓  		      |")
	print("            ▓  |         ▓ 		      |")
	print("            ▓            ▓		      |")
	print("         ▓▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ ▓		      |")
	print("         ▀▀█▀▀▀▀▀▀▀▀▀▀▀▀▀█▀▀                  |")      
	print("           ▓  ▀█▀   ▄▀▀▄ ▓    ( Account       |")     
	print("            ▓     | ▀▄▄▀ ▓       is Invalid   |")
	print("            ▓    ___  |  ▓   O      m'lord  ) |")   
	print("            ▓    ▀▀▀  |_ ▓ o                  |")
	print("             ▓    .     ▓                     |")
	print("              ▀▀▀▀▀▀▀▀▀▀                      |")
	print("                ▓▓▄▓▓                         |")
	print("                 ▀ ▀                          |")
	print("  Adb Shell Account Checker - v.1.3")
	print("  ----------------------------------\n")

def AllDone():         
	print("  _____ _                 _  __              _ ")
	print(" / ____(_)          /\   | |/ _|            | |")
	print(" | (___ _ _ __     /  \  | | |_ _ __ ___  __| |")
	print(" \___ \| | '__|   / /\ \ | |  _| '__/ _ \/ _` |")
	print(" ____) | | |     / ____ \| | | | | |  __/ (_| |")
	print("|_____/|_|_|    /_/    \_\_|_| |_|  \___|\__,_|")
	print("▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
	print("				              |")       
	print("              ▄▄▄▄▄▄▄▄▄▄            	      |")
	print("             ▓        _ ▓  		      |")
	print("            ▓  |         ▓ 		      |")
	print("            ▓            ▓		      |")
	print("         ▓▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ ▓		      |")
	print("         ▀▀█▀▀▀▀▀▀▀▀▀▀▀▀▀█▀▀                  |")      
	print("           ▓  ▀█▀   ▄▀▀▄ ▓    ( All Done      |")     
	print("            ▓     | ▀▄▄▀ ▓          Here,     |")
	print("            ▓    ___  |  ▓   O      m'lord  ) |")   
	print("            ▓    ▀▀▀  |_ ▓ o                  |")
	print("             ▓    .     ▓                     |")
	print("              ▀▀▀▀▀▀▀▀▀▀                      |")
	print("                ▓▓▄▓▓                         |")
	print("                 ▀ ▀                          |")
	print("  Adb Shell Account Checker - v.1.3")
	print("  ----------------------------------\n")

def UserInfo(length,users,passwords):
	print("A total of "+str(length)+" combos are being attempted\n")
	print("Trying Combo: "+str(users)+":"+str(passwords)+"\n")
	return

def options():
	print("1) Express VPN | 2) IpVanish | 3) Nord VPN")
